version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile-dev
    working_dir: /app
    user: 1000:1000
    volumes:
      - ./lsp:/app
    stdin_open: true
    command: yarn dev
    ports:
      - 3000:3000
