services:
  backend: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    # image: lsp_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - ./backend:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  frontend:
    image: node:22.11.0-bookworm-slim
    working_dir: /app
    user: 1000:1000
    volumes:
      - ./frontend:/app
    # stdin_open: true
    command: yarn dev
    # command: sleep infinity
    ports:
      - 3000:3000

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    # image: lsp_production_postgres
    # container_name: lsp_local_postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    # container_name: lsp_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    # container_name: lsp_local_redis
    volumes:
      - ./data/redis_data:/data

  # Servidor Web NGINX
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      # Arquivo de configuração do Ngnix para este ambiente.
      - ./compose/local/nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      # Diretório onde o backend manipula arquivos, e que deve ficar acessivel ao servidor web.
      - ./data/tmp:/var/www/data
    depends_on:
      - backend
      - frontend
      # - flower
      # - mailpit
      # - daiquiri


      # celeryworker:
      #   <<: *django
      #   image: lsp_local_celeryworker
      #   container_name: lsp_local_celeryworker
      #   depends_on:
      #     - redis
      #     - postgres
      #     - mailpit
      #   ports: []
      #   command: /start-celeryworker

      # celerybeat:
      #   <<: *django
      #   image: lsp_local_celerybeat
      #   container_name: lsp_local_celerybeat
      #   depends_on:
      #     - redis
      #     - postgres
      #     - mailpit
      #   ports: []
      #   command: /start-celerybeat

      # flower:
      #   <<: *django
      #   image: lsp_local_flower
      #   container_name: lsp_local_flower
      #   ports:
      #     - '5555:5555'
      #   command: /start-flower      
