export const metadata = {
  title: "LIneA IDAC",
  description: "Generated by create next app",
};

export default function IdacRootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
