export const metadata = {
  title: "LIneA Science Platform",
  description: "Generated by create next app",
};

export default function LspRootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
