version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile-dev
    working_dir: /app
    user: 1000:1000
    environment:
      # Use lsp-dev for testing enviroment lsp-dev.linea.org.br
      # Use lsp-production for production enviroment lsp.linea.org.br
      # Em branco para ambiente de desenvolvimento (localhost)
      - NEXT_PUBLIC_ENVIROMENT=lsp-dev
    volumes:
      - ./lsp:/app
    stdin_open: true
    command: yarn dev
    ports:
      - 3000:3000
