version: "3.9"

services:
  frontend:
    image: linea/lsp_landing_page:latest
    command: yarn start
    environment:
        # Use lsp-dev for testing enviroment lsp-dev.linea.org.br
        # Use lsp-production for production enviroment lsp.linea.org.br
        # Em branco para ambiente de desenvolvimento (localhost)
      - NEXT_PUBLIC_ENVIROMENT=lsp-production

  nginx:
    image: nginx:1.21.6-alpine
    ports:
      # ATENÇÃO: Altere a porta para uma porta compativel com o ambiente.
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
