name: Build and Push Docker Images

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:

  build_frontend:
    name: Build and Push Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: linea/lsp_landing_page
          tags: |
            type=raw,enable=${{ startsWith(github.ref, 'refs/tags/v') }},priority=100,value=latest
            type=semver,enable=true,priority=200,prefix=v,suffix=,pattern={{version}}
            type=sha,enable=true,priority=300,suffix=,format=short            
          flavor: |
            latest=false
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
